<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: ochoscar
 * Date: Fri, 03 May 2013 23:15:48 +0000
 */

$conf['title'] = 'ochoscar';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['proxy']['user'] = 'ochoscar';
$conf['proxy']['pass'] = '<b>anVhcmV6';
$conf['plugin']['latex']['preamble'] = '\\documentclass[10pt]{article}

\\usepackage[utf8]{inputenc}

\\usepackage{amsmath}

\\usepackage{amsfonts}

\\usepackage{amssymb}

\\usepackage{color}

\\pagestyle{empty}

\\begin{document}

\\definecolor{MyColour}{rgb}{0.50,0.00,0.00}

{\\color{MyColour}';

// end auto-generated content
